from typing import Hashable

__all__ = ['add', 'get', 'get_all']

def add(object, name: Hashable) -> None: ...
def get(name: Hashable) -> object: ...
def get_all(names: Hashable) -> list[object]: ...
