import pygame
from dataclasses import dataclass

@dataclass
class GridLayout:
    canvas: pygame.Rect
    cells_x: int
    cells_y: int
    margin_x: int = ...
    margin_y: int = ...
    steps_x: float = ...
    steps_y: float = ...
    def __post_init__(self) -> None: ...
    def __call__(self, x: int, y: int, w: int = 1, h: int = 1) -> pygame.Rect: ...
    def offset(self, x: int, y: int, w: int = 1, h: int = 1) -> pygame.Point: ...
    position = __call__
    def cell(self, world_x: int, world_y: int) -> pygame.Point: ...

def debug_grid(screen, grid, color: str = 'grey20') -> None: ...
