from typing import Generator, Hashable

__all__ = ['StateMachine']

class NoRoot(Exception): ...
class OpenGraph(Exception): ...
class UnknownNode(Exception): ...
class UnknownFollowupIndex(Exception): ...

StateMachineState = Hashable

class StateMachine:
    states: dict[Hashable, object]
    root: Hashable
    def __init__(self, states=None) -> None: ...
    def add(self, name: StateMachineState, *followups: StateMachineState) -> None: ...
    def walker(self, entry: StateMachineState = None) -> Generator[object]: ...
